import { useState, useMemo } from "react";
import { trpc } from "../lib/trpc";
import { ChevronLeft, ChevronRight, Plus, Calendar as CalendarIcon, Clock, MapPin, X } from "lucide-react";
import { useToast } from "../hooks/use-toast";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "../components/ui/dialog";
import { Button } from "../components/ui/button";

interface CalendarEvent {
  id: number | string;
  title: string;
  description?: string | null;
  startDate: Date;
  endDate: Date;
  allDay: number | boolean;
  eventType: string;
  priority: string;
  projectId?: number | null;
  projectName?: string | null;
  location?: string | null;
  color?: string | null;
  status: string;
  isAutoGenerated?: boolean;
}

export default function CalendarPage() {
  const { toast } = useToast();
  const [currentDate, setCurrentDate] = useState(new Date());
  const [selectedDate, setSelectedDate] = useState<Date | null>(null);
  const [showEventModal, setShowEventModal] = useState(false);
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [selectedEvent, setSelectedEvent] = useState<CalendarEvent | null>(null);

  // Form state
  const [eventForm, setEventForm] = useState({
    title: "",
    description: "",
    startDate: new Date(),
    endDate: new Date(),
    allDay: true,
    eventType: "meeting" as const,
    priority: "medium" as const,
    projectId: undefined as number | undefined,
    location: "",
    color: "#C9A882",
  });

  // Get first and last day of current month
  const firstDayOfMonth = useMemo(() => {
    return new Date(currentDate.getFullYear(), currentDate.getMonth(), 1);
  }, [currentDate]);

  const lastDayOfMonth = useMemo(() => {
    return new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 0);
  }, [currentDate]);

  // Query events
  const { data: events = [], refetch: refetchEvents } = trpc.calendar.getEventsByDateRange.useQuery({
    startDate: firstDayOfMonth,
    endDate: lastDayOfMonth,
  });

  // Query project deadlines
  const { data: deadlines = [] } = trpc.calendar.getProjectDeadlines.useQuery();

  // Combine events and deadlines
  const allEvents = useMemo(() => {
    const combinedEvents = [...events, ...deadlines];
    return combinedEvents.map((event) => ({
      ...event,
      startDate: new Date(event.startDate),
      endDate: new Date(event.endDate),
    }));
  }, [events, deadlines]);

  // Mutations
  const createEventMutation = trpc.calendar.createEvent.useMutation({
    onSuccess: () => {
      toast({
        title: "Evento criado",
        description: "O evento foi criado com sucesso.",
      });
      refetchEvents();
      setShowCreateModal(false);
      resetForm();
    },
    onError: (error) => {
      toast({
        title: "Erro ao criar evento",
        description: error.message,
        variant: "destructive",
      });
    },
  });

  const deleteEventMutation = trpc.calendar.deleteEvent.useMutation({
    onSuccess: () => {
      toast({
        title: "Evento eliminado",
        description: "O evento foi eliminado com sucesso.",
      });
      refetchEvents();
      setShowEventModal(false);
      setSelectedEvent(null);
    },
    onError: (error) => {
      toast({
        title: "Erro ao eliminar evento",
        description: error.message,
        variant: "destructive",
      });
    },
  });

  // Generate calendar days
  const calendarDays = useMemo(() => {
    const days = [];
    const firstDay = firstDayOfMonth.getDay(); // 0 = Sunday
    const daysInMonth = lastDayOfMonth.getDate();

    // Add empty cells for days before month starts
    for (let i = 0; i < firstDay; i++) {
      days.push(null);
    }

    // Add days of month
    for (let day = 1; day <= daysInMonth; day++) {
      days.push(new Date(currentDate.getFullYear(), currentDate.getMonth(), day));
    }

    return days;
  }, [currentDate, firstDayOfMonth, lastDayOfMonth]);

  // Get events for a specific day
  const getEventsForDay = (date: Date | null) => {
    if (!date) return [];
    return allEvents.filter((event) => {
      const eventDate = new Date(event.startDate);
      return (
        eventDate.getDate() === date.getDate() &&
        eventDate.getMonth() === date.getMonth() &&
        eventDate.getFullYear() === date.getFullYear()
      );
    });
  };

  const handlePreviousMonth = () => {
    setCurrentDate(new Date(currentDate.getFullYear(), currentDate.getMonth() - 1, 1));
  };

  const handleNextMonth = () => {
    setCurrentDate(new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 1));
  };

  const handleDayClick = (date: Date | null) => {
    if (!date) return;
    setSelectedDate(date);
    const dayEvents = getEventsForDay(date);
    if (dayEvents.length > 0) {
      setSelectedEvent(dayEvents[0]);
      setShowEventModal(true);
    } else {
      setEventForm({ ...eventForm, startDate: date, endDate: date });
      setShowCreateModal(true);
    }
  };

  const handleCreateEvent = () => {
    if (!eventForm.title) {
      toast({
        title: "Título obrigatório",
        description: "Por favor, insira um título para o evento.",
        variant: "destructive",
      });
      return;
    }

    createEventMutation.mutate({
      ...eventForm,
      allDay: eventForm.allDay,
    });
  };

  const handleDeleteEvent = () => {
    if (!selectedEvent || selectedEvent.isAutoGenerated) return;
    if (typeof selectedEvent.id === "string") return; // Can't delete auto-generated events
    
    if (confirm("Tem a certeza que deseja eliminar este evento?")) {
      deleteEventMutation.mutate({ eventId: selectedEvent.id as number });
    }
  };

  const resetForm = () => {
    setEventForm({
      title: "",
      description: "",
      startDate: new Date(),
      endDate: new Date(),
      allDay: true,
      eventType: "meeting",
      priority: "medium",
      projectId: undefined,
      location: "",
      color: "#C9A882",
    });
  };

  const monthNames = [
    "Janeiro",
    "Fevereiro",
    "Março",
    "Abril",
    "Maio",
    "Junho",
    "Julho",
    "Agosto",
    "Setembro",
    "Outubro",
    "Novembro",
    "Dezembro",
  ];

  const dayNames = ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"];

  const eventTypeLabels: Record<string, string> = {
    meeting: "Reunião",
    deadline: "Prazo",
    delivery: "Entrega",
    site_visit: "Visita de Obra",
    presentation: "Apresentação",
    milestone: "Marco",
    personal: "Pessoal",
    other: "Outro",
  };

  const priorityColors: Record<string, string> = {
    low: "#95A5A6",
    medium: "#3498DB",
    high: "#F39C12",
    urgent: "#E74C3C",
  };

  return (
    <div className="min-h-screen" style={{ backgroundColor: "#F2F0E7" }}>
      <div className="container mx-auto py-8">
        {/* Header */}
        <div className="flex items-center justify-between mb-8">
          <div>
            <h1 className="text-3xl font-bold mb-2" style={{ fontFamily: "'Cormorant Garamond', serif", color: "#5F5C59" }}>
              Calendário
            </h1>
            <p className="text-gray-600">Gestão de eventos, prazos e compromissos</p>
          </div>
          <button
            onClick={() => setShowCreateModal(true)}
            className="flex items-center gap-2 px-6 py-3 rounded-lg font-medium transition-colors"
            style={{ backgroundColor: "#C9A882", color: "#FFFFFF" }}
          >
            <Plus className="w-4 h-4" />
            Novo Evento
          </button>
        </div>

        {/* Calendar Navigation */}
        <div className="bg-white rounded-lg p-6 border border-gray-200">
          <div className="flex items-center justify-between mb-6">
            <button
              onClick={handlePreviousMonth}
              className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
              style={{ color: "#5F5C59" }}
            >
              <ChevronLeft className="w-5 h-5" />
            </button>
            <h2 className="text-2xl font-bold" style={{ fontFamily: "'Cormorant Garamond', serif", color: "#5F5C59" }}>
              {monthNames[currentDate.getMonth()]} {currentDate.getFullYear()}
            </h2>
            <button
              onClick={handleNextMonth}
              className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
              style={{ color: "#5F5C59" }}
            >
              <ChevronRight className="w-5 h-5" />
            </button>
          </div>

          {/* Day Names */}
          <div className="grid grid-cols-7 gap-2 mb-2">
            {dayNames.map((day) => (
              <div key={day} className="text-center font-semibold text-sm py-2" style={{ color: "#5F5C59" }}>
                {day}
              </div>
            ))}
          </div>

          {/* Calendar Grid */}
          <div className="grid grid-cols-7 gap-2">
            {calendarDays.map((date, index) => {
              const dayEvents = getEventsForDay(date);
              const isToday =
                date &&
                date.getDate() === new Date().getDate() &&
                date.getMonth() === new Date().getMonth() &&
                date.getFullYear() === new Date().getFullYear();

              return (
                <div
                  key={index}
                  onClick={() => handleDayClick(date)}
                  className={`min-h-24 p-2 border rounded-lg cursor-pointer transition-colors ${
                    date ? "hover:border-[#C9A882] bg-white" : "bg-gray-50"
                  } ${isToday ? "ring-2 ring-[#C9A882]" : "border-gray-200"}`}
                >
                  {date && (
                    <>
                      <div className={`text-sm font-medium mb-1 ${isToday ? "text-[#C9A882]" : "text-gray-700"}`}>
                        {date.getDate()}
                      </div>
                      <div className="space-y-1">
                        {dayEvents.slice(0, 2).map((event, idx) => (
                          <div
                            key={idx}
                            className="text-xs px-2 py-1 rounded truncate"
                            style={{
                              backgroundColor: event.color || "#C9A882",
                              color: "#FFFFFF",
                            }}
                          >
                            {event.title}
                          </div>
                        ))}
                        {dayEvents.length > 2 && (
                          <div className="text-xs text-gray-500 px-2">+{dayEvents.length - 2} mais</div>
                        )}
                      </div>
                    </>
                  )}
                </div>
              );
            })}
          </div>
        </div>

        {/* Upcoming Events */}
        <div className="mt-6 bg-white rounded-lg p-6 border border-gray-200">
          <h3 className="font-semibold text-lg mb-4" style={{ color: "#5F5C59" }}>
            Próximos Eventos
          </h3>
          <div className="space-y-3">
            {allEvents
              .filter((event) => new Date(event.startDate) >= new Date())
              .slice(0, 5)
              .map((event) => (
                <div
                  key={typeof event.id === "number" ? event.id : event.id}
                  onClick={() => {
                    setSelectedEvent(event);
                    setShowEventModal(true);
                  }}
                  className="flex items-center gap-4 p-4 bg-gray-50 rounded-lg hover:bg-gray-100 cursor-pointer transition-colors"
                >
                  <div className="w-2 h-2 rounded-full" style={{ backgroundColor: event.color || "#C9A882" }} />
                  <div className="flex-1">
                    <h4 className="font-medium" style={{ color: "#5F5C59" }}>
                      {event.title}
                    </h4>
                    <p className="text-sm text-gray-600">
                      {new Date(event.startDate).toLocaleDateString("pt-PT", {
                        day: "numeric",
                        month: "long",
                        year: "numeric",
                      })}
                    </p>
                  </div>
                  <span
                    className="px-3 py-1 text-xs rounded-full"
                    style={{
                      backgroundColor: priorityColors[event.priority] || "#95A5A6",
                      color: "#FFFFFF",
                    }}
                  >
                    {eventTypeLabels[event.eventType] || event.eventType}
                  </span>
                </div>
              ))}
            {allEvents.filter((event) => new Date(event.startDate) >= new Date()).length === 0 && (
              <p className="text-gray-500 text-sm">Nenhum evento próximo</p>
            )}
          </div>
        </div>
      </div>

      {/* Event Details Modal */}
      <Dialog open={showEventModal} onOpenChange={setShowEventModal}>
        <DialogContent className="bg-white">
          <DialogHeader>
            <DialogTitle style={{ color: "#5F5C59" }}>Detalhes do Evento</DialogTitle>
          </DialogHeader>
          {selectedEvent && (
            <div className="space-y-4">
              <div>
                <h3 className="text-xl font-bold mb-2" style={{ color: "#5F5C59" }}>
                  {selectedEvent.title}
                </h3>
                {selectedEvent.description && <p className="text-gray-600">{selectedEvent.description}</p>}
              </div>

              <div className="space-y-2">
                <div className="flex items-center gap-2 text-sm text-gray-600">
                  <CalendarIcon className="w-4 h-4" />
                  <span>
                    {new Date(selectedEvent.startDate).toLocaleDateString("pt-PT", {
                      day: "numeric",
                      month: "long",
                      year: "numeric",
                    })}
                  </span>
                </div>

                {!selectedEvent.allDay && (
                  <div className="flex items-center gap-2 text-sm text-gray-600">
                    <Clock className="w-4 h-4" />
                    <span>
                      {new Date(selectedEvent.startDate).toLocaleTimeString("pt-PT", {
                        hour: "2-digit",
                        minute: "2-digit",
                      })}{" "}
                      -{" "}
                      {new Date(selectedEvent.endDate).toLocaleTimeString("pt-PT", {
                        hour: "2-digit",
                        minute: "2-digit",
                      })}
                    </span>
                  </div>
                )}

                {selectedEvent.location && (
                  <div className="flex items-center gap-2 text-sm text-gray-600">
                    <MapPin className="w-4 h-4" />
                    <span>{selectedEvent.location}</span>
                  </div>
                )}

                {selectedEvent.projectName && (
                  <div className="flex items-center gap-2 text-sm">
                    <span className="font-medium" style={{ color: "#5F5C59" }}>
                      Projeto:
                    </span>
                    <span className="text-gray-600">{selectedEvent.projectName}</span>
                  </div>
                )}

                <div className="flex items-center gap-2">
                  <span
                    className="px-3 py-1 text-xs rounded-full"
                    style={{
                      backgroundColor: selectedEvent.color || "#C9A882",
                      color: "#FFFFFF",
                    }}
                  >
                    {eventTypeLabels[selectedEvent.eventType] || selectedEvent.eventType}
                  </span>
                  <span
                    className="px-3 py-1 text-xs rounded-full"
                    style={{
                      backgroundColor: priorityColors[selectedEvent.priority] || "#95A5A6",
                      color: "#FFFFFF",
                    }}
                  >
                    {selectedEvent.priority}
                  </span>
                </div>
              </div>

              {!selectedEvent.isAutoGenerated && typeof selectedEvent.id === "number" && (
                <div className="flex gap-2 pt-4">
                  <Button
                    onClick={handleDeleteEvent}
                    variant="destructive"
                    disabled={deleteEventMutation.isPending}
                  >
                    {deleteEventMutation.isPending ? "A eliminar..." : "Eliminar Evento"}
                  </Button>
                </div>
              )}

              {selectedEvent.isAutoGenerated && (
                <p className="text-xs text-gray-500 italic">Este é um prazo automático gerado a partir de um projeto.</p>
              )}
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* Create Event Modal */}
      <Dialog open={showCreateModal} onOpenChange={setShowCreateModal}>
        <DialogContent className="bg-white max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle style={{ color: "#5F5C59" }}>Criar Novo Evento</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Título *</label>
              <input
                type="text"
                value={eventForm.title}
                onChange={(e) => setEventForm({ ...eventForm, title: e.target.value })}
                placeholder="Ex: Reunião com cliente"
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#C9A882]"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Descrição</label>
              <textarea
                value={eventForm.description}
                onChange={(e) => setEventForm({ ...eventForm, description: e.target.value })}
                placeholder="Detalhes do evento..."
                rows={3}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#C9A882]"
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Data de Início</label>
                <input
                  type="date"
                  value={eventForm.startDate.toISOString().split("T")[0]}
                  onChange={(e) => setEventForm({ ...eventForm, startDate: new Date(e.target.value) })}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#C9A882]"
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Data de Fim</label>
                <input
                  type="date"
                  value={eventForm.endDate.toISOString().split("T")[0]}
                  onChange={(e) => setEventForm({ ...eventForm, endDate: new Date(e.target.value) })}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#C9A882]"
                />
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Tipo de Evento</label>
                <select
                  value={eventForm.eventType}
                  onChange={(e) => setEventForm({ ...eventForm, eventType: e.target.value as any })}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#C9A882]"
                >
                  <option value="meeting">Reunião</option>
                  <option value="deadline">Prazo</option>
                  <option value="delivery">Entrega</option>
                  <option value="site_visit">Visita de Obra</option>
                  <option value="presentation">Apresentação</option>
                  <option value="milestone">Marco</option>
                  <option value="personal">Pessoal</option>
                  <option value="other">Outro</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Prioridade</label>
                <select
                  value={eventForm.priority}
                  onChange={(e) => setEventForm({ ...eventForm, priority: e.target.value as any })}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#C9A882]"
                >
                  <option value="low">Baixa</option>
                  <option value="medium">Média</option>
                  <option value="high">Alta</option>
                  <option value="urgent">Urgente</option>
                </select>
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Localização</label>
              <input
                type="text"
                value={eventForm.location}
                onChange={(e) => setEventForm({ ...eventForm, location: e.target.value })}
                placeholder="Ex: Escritório, Obra X"
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#C9A882]"
              />
            </div>

            <div className="flex items-center gap-2">
              <input
                type="checkbox"
                checked={eventForm.allDay}
                onChange={(e) => setEventForm({ ...eventForm, allDay: e.target.checked })}
                className="w-4 h-4 rounded border-gray-300 text-[#C9A882] focus:ring-[#C9A882]"
              />
              <label className="text-sm text-gray-700">Evento de dia inteiro</label>
            </div>

            <div className="flex gap-2 pt-4">
              <button
                onClick={handleCreateEvent}
                disabled={createEventMutation.isPending}
                className="flex-1 px-6 py-3 rounded-lg font-medium transition-colors"
                style={{ backgroundColor: "#C9A882", color: "#FFFFFF" }}
              >
                {createEventMutation.isPending ? "A criar..." : "Criar Evento"}
              </button>
              <button
                onClick={() => {
                  setShowCreateModal(false);
                  resetForm();
                }}
                className="px-6 py-3 bg-gray-100 hover:bg-gray-200 rounded-lg font-medium transition-colors"
                style={{ color: "#5F5C59" }}
              >
                Cancelar
              </button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
