CREATE TABLE IF NOT EXISTS whatIfScenarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  projectId INT NOT NULL,
  scenarioName VARCHAR(255) NOT NULL,
  description TEXT,
  budgetAdjustment DECIMAL(15, 2),
  budgetPercentage INT,
  teamSizeAdjustment INT,
  timelineAdjustment INT,
  resourceAllocation TEXT,
  predictedDuration INT,
  predictedCost DECIMAL(15, 2),
  predictedDelayDays INT,
  costVariance DECIMAL(15, 2),
  feasibilityScore INT,
  riskLevel ENUM('low', 'medium', 'high', 'critical') NOT NULL DEFAULT 'medium',
  impactSummary TEXT,
  recommendations TEXT,
  tradeoffs TEXT,
  isFavorite INT NOT NULL DEFAULT 0,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX project_idx (projectId),
  INDEX favorite_idx (isFavorite)
);
