CREATE TABLE scenarioShares (
  id INT AUTO_INCREMENT PRIMARY KEY,
  scenarioId INT NOT NULL,
  sharedBy INT NOT NULL,
  sharedWith INT NOT NULL,
  permission ENUM('view', 'edit', 'admin') NOT NULL DEFAULT 'view',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE scenarioComments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  scenarioId INT NOT NULL,
  userId INT NOT NULL,
  comment TEXT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);
